# Dockerfile_nginx
# Define los pasos para construir una imagen personalizada de Nginx
# que contiene los archivos del frontend y la configuración.

# 1. Usar la imagen oficial y ligera de Nginx como base
FROM nginx:alpine

# 2. Copiar el archivo de configuración personalizado de Nginx
# Esto reemplazará la configuración por defecto de Nginx.
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# 3. Copiar todos los archivos del frontend
# Copia el contenido de tu carpeta local 'frontend' al directorio
# que Nginx utiliza para servir archivos estáticos.
COPY ./frontend/ /usr/share/nginx/html

# 4. Exponer el puerto 80 (puerto HTTP estándar)
EXPOSE 80

# 5. Comando para iniciar el servidor Nginx
# 'daemon off;' asegura que Nginx se ejecute en primer plano,
# lo cual es necesario para que el contenedor siga funcionando.
CMD ["nginx", "-g", "daemon off;"]
