"""Crear tabla para RAGSettings"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2fd17aae68'
down_revision = '552fcb7aaff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_settings_id'), 'rag_settings', ['id'], unique=False)
    op.alter_column('Incidents', 'ticket_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'1000'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Incidents', 'ticket_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'1000'::character varying"))
    op.drop_index(op.f('ix_rag_settings_id'), table_name='rag_settings')
    op.drop_table('rag_settings')
    # ### end Alembic commands ###
