"""Add is_active field to Incidents table"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380c41ca8eb3'
down_revision = 'd681074868fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the is_active column to Incidents table
    op.add_column('Incidents', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Update existing NULL hashed_password to an empty string
    op.execute('UPDATE "Users" SET hashed_password = \'\' WHERE hashed_password IS NULL')

    # Now, alter the column to be non-nullable
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('Incidents', 'is_active')
    # ### end Alembic commands ###
