"""add_hash_to_evidence_file"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4159004c8d22'
down_revision = 'ccab73c18ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EvidenceFiles', sa.Column('file_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EvidenceFiles', 'file_hash')
    # ### end Alembic commands ###
