"""Drop impact_scores column from Incidents table"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552fcb7aaff7'
down_revision = 'a170020eb6b4'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('Incidents', 'impact_scores')
	 # ### end Alembic commands ###
def downgrade():
	# ### commands auto generated by Alembic - please adjust! ##
	op.add_column('Incidents', sa.Column('impact_scores', sa.JSON(), nullable=True))
        # ### end Alembic commands ###

