"""Re-add ai_recommendations to Incident model"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e713d9aa78'
down_revision = '2a2fd17aae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Incidents', sa.Column('ai_recommendations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Incidents', 'ai_recommendations')
    # ### end Alembic commands ###
