"""add_hierarchical_classification_and_assets"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdba2577e27'
down_revision = 'd84088ec45ab'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssetTypes',
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('asset_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_AssetTypes_asset_type_id'), 'AssetTypes', ['asset_type_id'], unique=False)
    op.create_table('AttackVectors',
    sa.Column('attack_vector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('attack_vector_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_AttackVectors_attack_vector_id'), 'AttackVectors', ['attack_vector_id'], unique=False)
    op.create_table('IncidentCategories',
    sa.Column('incident_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('incident_category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_IncidentCategories_incident_category_id'), 'IncidentCategories', ['incident_category_id'], unique=False)
    op.create_table('Assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['AssetTypes.asset_type_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_Assets_asset_id'), 'Assets', ['asset_id'], unique=False)
    op.create_table('IncidentTypes',
    sa.Column('incident_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('incident_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_category_id'], ['IncidentCategories.incident_category_id'], ),
    sa.PrimaryKeyConstraint('incident_type_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_IncidentTypes_incident_type_id'), 'IncidentTypes', ['incident_type_id'], unique=False)

    # --- Ajuste Manual ---
    op.drop_constraint('Incidents_classification_id_fkey', 'Incidents', type_='foreignkey')
    op.drop_column('Incidents', 'classification_id')
    op.drop_index(op.f('ix_IncidentClassifications_classification_id'), table_name='IncidentClassifications')
    op.drop_table('IncidentClassifications')
    # --- Fin del Ajuste Manual ---

    op.add_column('Incidents', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('incident_type_id', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('attack_vector_id', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('other_asset_location', sa.String(length=512), nullable=True))
    op.create_foreign_key('fk_incidents_asset_id', 'Incidents', 'Assets', ['asset_id'], ['asset_id'])
    op.create_foreign_key('fk_incidents_attack_vector_id', 'Incidents', 'AttackVectors', ['attack_vector_id'], ['attack_vector_id'])
    op.create_foreign_key('fk_incidents_incident_type_id', 'Incidents', 'IncidentTypes', ['incident_type_id'], ['incident_type_id'])
    op.drop_column('Incidents', 'location')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Incidents', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Incidents', sa.Column('classification_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_incidents_incident_type_id', 'Incidents', type_='foreignkey')
    op.drop_constraint('fk_incidents_attack_vector_id', 'Incidents', type_='foreignkey')
    op.drop_constraint('fk_incidents_asset_id', 'Incidents', type_='foreignkey')
    op.drop_column('Incidents', 'other_asset_location')
    op.drop_column('Incidents', 'attack_vector_id')
    op.drop_column('Incidents', 'incident_type_id')
    op.drop_column('Incidents', 'asset_id')

    op.create_table('IncidentClassifications',
    sa.Column('classification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('classification_id', name='IncidentClassifications_pkey')
    )
    op.create_index('ix_IncidentClassifications_classification_id', 'IncidentClassifications', ['classification_id'], unique=False)
    op.create_foreign_key('Incidents_classification_id_fkey', 'Incidents', 'IncidentClassifications', ['classification_id'], ['classification_id'])

    op.drop_index(op.f('ix_IncidentTypes_incident_type_id'), table_name='IncidentTypes')
    op.drop_table('IncidentTypes')
    op.drop_index(op.f('ix_Assets_asset_id'), table_name='Assets')
    op.drop_table('Assets')
    op.drop_index(op.f('ix_IncidentCategories_incident_category_id'), table_name='IncidentCategories')
    op.drop_table('IncidentCategories')
    op.drop_index(op.f('ix_AttackVectors_attack_vector_id'), table_name='AttackVectors')
    op.drop_table('AttackVectors')
    op.drop_index(op.f('ix_AssetTypes_asset_type_id'), table_name='AssetTypes')
    op.drop_table('AssetTypes')
    # ### end Alembic commands ###