"""Add group assignment and new fields to Incident model"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a170020eb6b4'
down_revision = '584ffc3f2980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Incidents', sa.Column('assigned_to_group_id', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('incident_category_id', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('impact_confidentiality', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('impact_integrity', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('impact_availability', sa.Integer(), nullable=True))
    op.add_column('Incidents', sa.Column('total_impact', sa.Integer(), nullable=True))
    op.create_foreign_key('Incidents_incident_category_id_fkey', 'Incidents', 'IncidentCategories', ['incident_category_id'], ['incident_category_id'])
    op.create_foreign_key('Incidents_assigned_to_group_id_fkey', 'Incidents', 'groups', ['assigned_to_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Incidents_assigned_to_group_id_fkey', 'Incidents', type_='foreignkey')
    op.drop_constraint('Incidents_incident_category_id_fkey', 'Incidents', type_='foreignkey')
    op.drop_column('Incidents', 'total_impact')
    op.drop_column('Incidents', 'impact_availability')
    op.drop_column('Incidents', 'impact_integrity')
    op.drop_column('Incidents', 'impact_confidentiality')
    op.drop_column('Incidents', 'incident_category_id')
    op.drop_column('Incidents', 'assigned_to_group_id')
    # ### end Alembic commands ###
