"""Fix hashed_password nullable"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be822f6a477e'
down_revision = 'bfb22caec2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
