"""create_knowledge_curation_table"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccab73c18ac3'
down_revision = 'f3fa31625422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_curation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('flagged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_curation_chunk_id'), 'knowledge_curation', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_curation_id'), 'knowledge_curation', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_curation_source_name'), 'knowledge_curation', ['source_name'], unique=False)
    op.create_index(op.f('ix_knowledge_curation_status'), 'knowledge_curation', ['status'], unique=False)
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_knowledge_curation_status'), table_name='knowledge_curation')
    op.drop_index(op.f('ix_knowledge_curation_source_name'), table_name='knowledge_curation')
    op.drop_index(op.f('ix_knowledge_curation_id'), table_name='knowledge_curation')
    op.drop_index(op.f('ix_knowledge_curation_chunk_id'), table_name='knowledge_curation')
    op.drop_table('knowledge_curation')
    # ### end Alembic commands ###
